apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: demo-namespace
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31131
    protocol: TCP
  selector:
    app: demo-app